<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeds all 550 FNRI Food Exchange List items (4th Edition, 2020).
 *
 * Column order in each row:
 *  [0]  id
 *  [1]  category_id      (1=Vegetable, 2=Fruit, 3=Milk, 4=Rice, 5=Meat, 6=Fat, 7=Sugar)
 *  [2]  name             Filipino/English name
 *  [3]  local_name       Common local alias (nullable)
 *  [4]  subcategory      e.g. fresh, processed, free, low_fat, high_fat, sugar
 *  [5]  ep_grams         Edible portion in grams (nullable)
 *  [6]  household_measure e.g. '1/2 cup raw'
 *  [7]  is_high_sodium
 *  [8]  is_high_potassium
 *  [9]  is_high_phosphorus
 *  [10] is_high_fiber
 *  [11] is_low_gi
 *  [12] ok_for_diabetes
 *  [13] ok_for_hypertension
 *  [14] ok_for_renal
 *  [15] is_free_food     (<16 kcal per serving)
 *  [16] notes
 *
 * DO NOT alter seed data — it is the authoritative FNRI FEL reference.
 * Run with: php artisan db:seed --class=FoodExchangeItemSeeder
 */
class FoodExchangeItemSeeder extends Seeder
{
    public function run(): void
    {
        // Skip if already seeded
        if (DB::table('food_exchange_items')->count() >= 550) {
            $this->command->info('FEL food items already seeded (550 items found). Skipping.');
            return;
        }

        $this->command->info('Seeding 550 FNRI FEL food items...');

        $columns = [
            'id', 'category_id', 'name', 'local_name', 'subcategory',
            'ep_grams', 'household_measure',
            'is_high_sodium', 'is_high_potassium', 'is_high_phosphorus',
            'is_high_fiber', 'is_low_gi',
            'ok_for_diabetes', 'ok_for_hypertension', 'ok_for_renal',
            'is_free_food', 'notes',
        ];

        // Insert in chunks of 50 to avoid max_allowed_packet limits
        foreach (array_chunk($this->items(), 50) as $chunk) {
            $rows = array_map(fn($row) => array_combine($columns, $row), $chunk);
            DB::table('food_exchange_items')->insertOrIgnore($rows);
        }

        $count = DB::table('food_exchange_items')->count();
        $this->command->info("FEL food items seeded: {$count} items in database.");
    }

    /**
     * All 550 FNRI FEL food items.
     * Source: FNRI Food Exchange List 4th Edition (2020).
     */
    private function items(): array
    {
        return [
            [1, 1, 'Alagaw, dahon', null, 'fresh', 40.00, '1/2 cup raw', false, false, false, false, false, true, true, true, false, null],
            [2, 1, 'Langka, hilaw', 'Young jackfruit', 'fresh', 45.00, '1/2 cup cooked', false, false, false, false, false, true, true, true, false, null],
            [3, 1, 'Ampalaya, dahon', 'Bitter gourd leaves', 'fresh', 40.00, '1/2 cup raw', false, false, false, true, false, true, true, true, false, null],
            [4, 1, 'Malunggay, dahon', 'Moringa leaves', 'fresh', 40.00, '1/2 cup raw', false, false, false, true, false, true, true, true, false, null],
            [5, 1, 'Artichoke', null, 'fresh', 40.00, '1/2 cup raw', false, false, false, true, false, true, true, true, false, null],
            [6, 1, 'Paayap, bunga', 'Yard-long beans', 'fresh', 45.00, '1/2 cup cooked', false, false, false, true, false, true, true, true, false, null],
            [7, 1, 'Broccoli', null, 'fresh', 45.00, '1/2 cup cooked', false, false, false, true, false, true, true, true, false, null],
            [8, 1, 'Patani, bunga', 'Lima beans', 'fresh', 45.00, '1/2 cup cooked', false, false, false, true, false, true, true, true, false, null],
            [9, 1, 'Carrot', 'Karot', 'fresh', 45.00, '1/2 cup cooked', false, false, false, false, false, true, true, true, false, null],
            [10, 1, 'Remolacha', 'Beets', 'fresh', 45.00, '1/2 cup cooked', false, false, false, false, false, true, true, true, false, null],
            [11, 1, 'Gabi, dahon', 'Taro leaves', 'fresh', 40.00, '1/2 cup raw', false, false, false, false, false, true, true, true, false, null],
            [12, 1, 'Rimas, bunga', 'Breadfruit', 'fresh', 45.00, '1/2 cup cooked', false, false, false, false, false, true, true, true, false, null],
            [13, 1, 'Himbaba-o, bulaklak', null, 'fresh', 40.00, '1/2 cup raw', false, false, false, false, false, true, true, true, false, null],
            [14, 1, 'Saluyot, dahon', 'Jute leaves', 'fresh', 40.00, '1/2 cup raw', false, false, false, true, false, true, true, true, false, null],
            [15, 1, 'Himbaba-o, dahon', null, 'fresh', 40.00, '1/2 cup raw', false, false, false, false, false, true, true, true, false, null],
            [16, 1, 'Sibuyas, ulo', 'Onion bulb', 'fresh', 45.00, '1/2 cup cooked', false, false, false, false, false, true, true, true, false, null],
            [17, 1, 'Kabuti, sariwa', 'Fresh mushroom', 'fresh', 40.00, '1/2 cup raw', false, false, false, false, false, true, true, true, false, null],
            [18, 1, 'Singkamas, bunga', 'Jicama fruit', 'fresh', 40.00, '1/2 cup raw', false, false, false, true, false, true, true, true, false, null],
            [19, 1, 'Kadyos, bunga', 'Pigeon peas', 'fresh', 45.00, '1/2 cup cooked', false, false, false, true, false, true, true, true, false, null],
            [20, 1, 'Sitaw, bunga', 'String beans', 'fresh', 45.00, '1/2 cup cooked', false, false, false, true, false, true, true, true, false, null],
            [21, 1, 'Kalabasa, bunga', 'Squash', 'fresh', 45.00, '1/2 cup cooked', false, false, false, true, false, true, true, true, false, null],
            [22, 1, 'Sitsaro', 'Snow peas', 'fresh', 45.00, '1/2 cup cooked', false, false, false, true, false, true, true, true, false, null],
            [23, 1, 'Kalabasa, dahon', 'Squash leaves', 'fresh', 40.00, '1/2 cup raw', false, false, false, false, false, true, true, true, false, null],
            [24, 1, 'Toge', 'Bean sprouts', 'fresh', 40.00, '1/2 cup raw', false, false, false, false, false, true, true, true, false, null],
            [25, 1, 'Kamansi, bunga', 'Breadnut', 'fresh', 45.00, '1/2 cup cooked', false, false, false, false, false, true, true, true, false, null],
            [26, 1, 'Ubod, niyog', 'Heart of palm', 'fresh', 40.00, '1/2 cup raw', false, false, false, true, false, true, true, true, false, null],
            [27, 1, 'Katuray, dahon', null, 'fresh', 40.00, '1/2 cup raw', false, false, false, false, false, true, true, true, false, null],
            [28, 1, 'Yakon', 'Yacon', 'fresh', 40.00, '1/2 cup raw', false, false, false, false, false, true, true, true, false, null],
            [29, 1, 'Asparagus, de lata', 'Canned asparagus', 'processed', null, '1 cup', false, false, false, false, false, true, true, true, false, null],
            [30, 1, 'Mais, mura, de lata', 'Canned young corn', 'processed', 75.00, '2 pcs', false, false, false, false, false, true, true, true, false, null],
            [31, 1, 'Garbansos, de lata', 'Canned chickpeas', 'processed', null, '1 tbsp', false, false, false, false, false, true, true, true, false, null],
            [32, 1, 'Green peas, de lata/frozen', null, 'processed', null, '1 tbsp', false, false, false, false, false, true, true, true, false, null],
            [33, 1, 'Mixed vegetables, frozen', null, 'processed', null, '2 tbsp', false, false, false, false, false, true, true, true, false, null],
            [34, 1, 'Mushroom, de lata', 'Canned mushroom', 'processed', null, '3/4 cup', false, false, false, false, false, true, true, true, false, null],
            [35, 1, 'Kamatis, de lata', 'Canned tomatoes', 'processed', null, '3 tbsp', false, false, false, false, false, true, true, true, false, null],
            [36, 1, 'Tomato juice, de lata', 'Canned tomato juice', 'processed', null, '1/4 cup', false, false, false, false, false, true, true, true, false, null],
            [37, 1, 'Water chestnut, de lata', 'Canned water chestnut', 'processed', 40.00, '4 pcs', false, false, false, false, false, true, true, true, false, null],
            [38, 1, 'Abitsuelas, bunga', 'Snap beans', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [39, 1, 'Okra', null, 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [40, 1, 'Alugbati, dahon', 'Malabar spinach', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [41, 1, 'Pako, dahon', 'Fern leaves', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [42, 1, 'Ampalaya, bunga', 'Bitter gourd fruit', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [43, 1, 'Papaya, bunga, hilaw', 'Green papaya', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [44, 1, 'Arugula', null, 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [45, 1, 'Patola, bunga', 'Sponge gourd', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [46, 1, 'Asparagus', null, 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [47, 1, 'Pechay Baguio', 'Baguio pechay', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [48, 1, 'Baby corn / young corn', null, 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [49, 1, 'Pechay, dahon', 'Bok choy', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [50, 1, 'Bataw, bunga', 'Hyacinth bean', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [51, 1, 'Pipino', 'Cucumber', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [52, 1, 'Bok choy', null, 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [53, 1, 'Puso ng saging, butuan', 'Banana blossom', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [54, 1, 'Cauliflower', 'Koliplor', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [55, 1, 'Repolyo', 'Cabbage', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [56, 1, 'Kalabasa, bulaklak', 'Squash flower', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [57, 1, 'Sayote, bunga', 'Chayote fruit', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [58, 1, 'Kale', null, 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [59, 1, 'Sayote, dahon', 'Chayote leaves', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [60, 1, 'Kamatis', 'Tomato', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [61, 1, 'Seaweed (balbalulang, lato, lukot)', null, 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [62, 1, 'Kamote, dahon', 'Sweet potato leaves', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [63, 1, 'Sigarilyas, bunga', 'Winged bean', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [64, 1, 'Kamoteng kahoy, dahon', 'Cassava leaves', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [65, 1, 'Sili, lara', 'Bell pepper', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [66, 1, 'Kangkong, dahon', 'Water spinach', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [67, 1, 'Singkamas, ugat', 'Jicama root', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [68, 1, 'Katuray, bulaklak', null, 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [69, 1, 'Sitaw, talbos', 'String bean tops', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [70, 1, 'Labanos', 'Radish', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [71, 1, 'Spinach, dahon', 'Spinach', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [72, 1, 'Labong', 'Bamboo shoots', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [73, 1, 'Upo, bunga', 'Bottle gourd', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [74, 1, 'Letsugas, dahon at tangkay', 'Lettuce', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [75, 1, 'Talinum, dahon', 'Talinum leaves', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [76, 1, 'Malunggay, bunga', 'Moringa flowers', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [77, 1, 'Talong', 'Eggplant', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [78, 1, 'Mustasa, dahon', 'Mustard leaves', 'free', null, 'As desired', false, false, false, false, false, true, true, true, true, 'Negligible calories'],
            [79, 2, 'Alimuran', null, 'fresh', 50.00, '13 pcs', false, false, false, false, false, true, true, true, false, null],
            [80, 2, 'Atis', 'Sugar apple', 'fresh', 10.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [81, 2, 'Balimbing', 'Starfruit', 'fresh', 160.00, '4 1/2 pieces', false, false, false, false, false, true, true, true, false, null],
            [82, 2, 'Bayabas, pula', 'Red guava', 'fresh', 60.00, '2 pieces', false, true, false, false, false, true, true, true, false, null],
            [83, 2, 'Bayabas, puti', 'White guava', 'fresh', 80.00, '3 pieces', false, true, false, false, false, true, true, true, false, null],
            [84, 2, 'Bignay', null, 'fresh', 200.00, '2 cups', false, false, false, false, false, true, true, true, false, null],
            [85, 2, 'Blueberries', null, 'fresh', 80.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [86, 2, 'Camachili', 'Manila tamarind', 'fresh', 55.00, '7 pods', false, false, false, false, false, true, true, true, false, null],
            [87, 2, 'Cherries, hinog', 'Ripe cherries', 'fresh', 70.00, '7 pieces', false, false, false, false, false, true, true, true, false, null],
            [88, 2, 'Chico', 'Sapodilla', 'fresh', 45.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [89, 2, 'Dalandan', 'Local orange', 'fresh', 155.00, '3 pieces', false, false, false, false, false, true, true, true, false, null],
            [90, 2, 'Datiles / Aratiles', null, 'fresh', 50.00, '1/4 cup or 25 pcs', false, false, false, false, false, true, true, true, false, null],
            [91, 2, 'Dragon Fruit', null, 'fresh', 75.00, '1/2 cup or 1/4 pc', false, false, false, false, false, true, true, true, false, null],
            [92, 2, 'Duhat', 'Java plum', 'fresh', 60.00, '12 pieces', false, false, false, false, false, true, true, true, false, null],
            [93, 2, 'Durian', null, 'fresh', 30.00, '2 segments', false, true, false, false, false, true, true, true, false, null],
            [94, 2, 'Granada', 'Pomegranate', 'fresh', 80.00, '1/2 piece', false, false, false, false, false, true, true, true, false, null],
            [95, 2, 'Guyabano', 'Soursop', 'fresh', 75.00, '1 slice', false, true, false, false, false, true, true, true, false, null],
            [96, 2, 'Kasuy, bunga', 'Cashew fruit', 'fresh', 70.00, '2 pieces', false, false, false, false, false, true, true, true, false, null],
            [97, 2, 'Kaymito, berde', 'Green star apple', 'fresh', 65.00, '1/2 piece', false, false, false, false, false, true, true, true, false, null],
            [98, 2, 'Kaymito, murado', 'Purple star apple', 'fresh', 65.00, '1/2 piece', false, false, false, false, false, true, true, true, false, null],
            [99, 2, 'Kiwifruit', null, 'fresh', 75.00, '1 piece', false, true, false, false, false, true, true, true, false, null],
            [100, 2, 'Langka, hinog', 'Ripe jackfruit', 'fresh', 40.00, '1 1/2 segments', false, true, false, false, false, true, true, true, false, null],
            [101, 2, 'Lansones', 'Lanzones', 'fresh', 80.00, '5 pieces', false, false, false, false, false, true, true, true, false, null],
            [102, 2, 'Lechiyas', 'Lychee', 'fresh', 50.00, '4 pieces', false, false, false, false, false, true, true, true, false, null],
            [103, 2, 'Longan', null, 'fresh', 60.00, '13 pieces', false, false, false, false, false, true, true, true, false, null],
            [104, 2, 'Mabolo', 'Velvet apple', 'fresh', 60.00, '1/2 piece', false, false, false, false, false, true, true, true, false, null],
            [105, 2, 'Makopa', 'Wax apple', 'fresh', 150.00, '9 pieces', false, false, false, false, false, true, true, true, false, null],
            [106, 2, 'Mangga, indian, hilaw', 'Green Indian mango', 'fresh', 80.00, '1/2 cup or 1 pc', false, false, false, false, false, true, true, true, false, null],
            [107, 2, 'Mangga, kalabaw, hilaw', 'Green carabao mango', 'fresh', 70.00, '1/2 cup or 1 slice', false, true, false, false, false, true, true, true, false, null],
            [108, 2, 'Mangga, kalabaw, manibalang', 'Half-ripe carabao mango', 'fresh', 70.00, '1/2 cup or 1 slice', false, true, false, false, false, true, true, true, false, null],
            [109, 2, 'Mangga, kalabaw, hinog', 'Ripe carabao mango', 'fresh', 70.00, '1/2 cup or 1 slice', false, true, false, false, false, true, true, true, false, null],
            [110, 2, 'Mangga, paho, hilaw', 'Green paho mango', 'fresh', 60.00, '9 pieces', false, false, false, false, false, true, true, true, false, null],
            [111, 2, 'Mangga, piko, hilaw', 'Green piko mango', 'fresh', 60.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [112, 2, 'Mangga, piko, hinog', 'Ripe piko mango', 'fresh', 60.00, '1 slice', false, true, false, false, false, true, true, true, false, null],
            [113, 2, 'Mangga, piko, manibalang', 'Half-ripe piko mango', 'fresh', 60.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [114, 2, 'Mangga, supsupin, hinog', 'Ripe supsupin mango', 'fresh', 50.00, '1 piece', false, true, false, false, false, true, true, true, false, null],
            [115, 2, 'Mangosteen', null, 'fresh', 55.00, '2 pieces', false, false, false, false, false, true, true, true, false, null],
            [116, 2, 'Mansanas, berde', 'Green apple', 'fresh', 75.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [117, 2, 'Mansanas, pula', 'Red apple', 'fresh', 75.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [118, 2, 'Marang', null, 'fresh', 35.00, '10 pieces', false, false, false, false, false, true, true, true, false, null],
            [119, 2, 'Milon, honey dew', 'Honeydew melon', 'fresh', 100.00, '3/4 cup or 1 slice', false, true, false, false, false, true, true, true, false, null],
            [120, 2, 'Milon, kastila', 'Muskmelon', 'fresh', 200.00, '1 1/4 cup or 1 slice', false, true, false, false, false, true, true, true, false, null],
            [121, 2, 'Milon, tagalog', 'Local melon', 'fresh', 200.00, '1 1/4 cup or 1 slice', false, true, false, false, false, true, true, true, false, null],
            [122, 2, 'Orange, Florida', null, 'fresh', 100.00, '1/2 piece', false, false, false, false, false, true, true, true, false, null],
            [123, 2, 'Orange, kiat kiat', 'Calamondin orange', 'fresh', 80.00, '3 pieces', false, false, false, false, false, true, true, true, false, null],
            [124, 2, 'Orange, ponkan', 'Ponkan orange', 'fresh', 80.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [125, 2, 'Pakwan', 'Watermelon', 'fresh', 150.00, '1 cup or 1 slice', false, true, false, false, false, true, true, true, false, null],
            [126, 2, 'Papaya, hinog', 'Ripe papaya', 'fresh', 90.00, '3/4 cup or 1 slice', false, true, false, false, false, true, true, true, false, null],
            [127, 2, 'Passion fruit', 'Maracuya', 'fresh', 65.00, '1/4 cup or 2 pcs', false, false, false, false, false, true, true, true, false, null],
            [128, 2, 'Peras', 'Pear', 'fresh', 95.00, '3/4 cup or 1/2 pc', false, false, false, false, false, true, true, true, false, null],
            [129, 2, 'Persimon', 'Persimmon', 'fresh', 60.00, '1/2 piece', false, false, false, false, false, true, true, true, false, null],
            [130, 2, 'Pinya', 'Pineapple', 'fresh', 80.00, '1/2 cup or 1 slice', false, false, false, false, false, true, true, true, false, null],
            [131, 2, 'Rambutan', null, 'fresh', 55.00, '5 pieces', false, false, false, false, false, true, true, true, false, null],
            [132, 2, 'Saging, bungulan', 'Bungulan banana', 'fresh', 40.00, '1/2 piece', false, true, false, false, false, true, true, true, false, null],
            [133, 2, 'Saging, cavendish, hinog', 'Ripe cavendish banana', 'fresh', 40.00, '1/2 piece', false, true, false, false, false, true, true, true, false, null],
            [134, 2, 'Saging, gloria', 'Gloria banana', 'fresh', 40.00, '1/2 piece', false, true, false, false, false, true, true, true, false, null],
            [135, 2, 'Saging, lakatan', 'Lakatan banana', 'fresh', 40.00, '1/2 piece', false, true, false, false, false, true, true, true, false, null],
            [136, 2, 'Saging, latundan', 'Latundan banana', 'fresh', 40.00, '1/2 piece', false, true, false, false, false, true, true, true, false, null],
            [137, 2, 'Saging, murado', 'Murado banana', 'fresh', 40.00, '1/2 piece', false, true, false, false, false, true, true, true, false, null],
            [138, 2, 'Saging, saba', 'Saba banana', 'fresh', 40.00, '1/2 piece', false, true, false, false, false, true, true, true, false, null],
            [139, 2, 'Sampalok, hinog', 'Ripe tamarind', 'fresh', 15.00, '12 segments', false, false, false, false, false, true, true, true, false, null],
            [140, 2, 'Santol', null, 'fresh', 65.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [141, 2, 'Singkamas, ugat', 'Jicama root', 'fresh', 200.00, '1 cup or 1 1/2 pcs', false, false, false, false, false, true, true, true, false, null],
            [142, 2, 'Siniguwelas', 'Spanish plum', 'fresh', 50.00, '4 pieces', false, false, false, false, false, true, true, true, false, null],
            [143, 2, 'Strawberry', null, 'fresh', 165.00, '1 1/4 cups', false, false, false, false, false, true, true, true, false, null],
            [144, 2, 'Suha', 'Pomelo', 'fresh', 100.00, '2 segments', false, false, false, false, false, true, true, true, false, null],
            [145, 2, 'Tiesa', 'Canistel', 'fresh', 30.00, '1/4 pc or 1 slice', false, false, false, false, false, true, true, true, false, null],
            [146, 2, 'Ubas', 'Grapes', 'fresh', 55.00, '12 pieces', false, false, false, false, false, true, true, true, false, null],
            [147, 2, 'Lemon juice', null, 'juice', 130.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [148, 2, 'Niyog, tubig', 'Coconut water', 'juice', 240.00, '1 cup', false, false, false, false, false, true, true, true, false, null],
            [149, 2, 'Orange juice', null, 'juice', 90.00, '1/3 cup', false, false, false, false, false, true, true, true, false, null],
            [150, 2, 'Passion fruit juice', null, 'juice', 65.00, '1/4 cup', false, false, false, false, false, true, true, true, false, null],
            [151, 2, 'Apple sauce, sweetened', null, 'canned', 60.00, '4 tbsp', false, false, false, false, false, true, true, true, false, null],
            [152, 2, 'Apple sauce, unsweetened', null, 'canned', 100.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [153, 2, 'Blackberries, heavy syrup', null, 'canned', 45.00, '1/4 cup or 9 pcs', false, false, false, false, false, true, true, true, false, null],
            [154, 2, 'Blackberries, light syrup, drained', null, 'canned', 45.00, '1/4 cup or 29 pcs', false, false, false, false, false, true, true, true, false, null],
            [155, 2, 'Fruit cocktail, tropical, in syrup', null, 'canned', 45.00, '1/4 cup', false, false, false, false, false, true, true, true, false, null],
            [156, 2, 'Lychee in syrup', null, 'canned', 45.00, '4 pieces', false, false, false, false, false, true, true, true, false, null],
            [157, 2, 'Peach halves in heavy syrup', null, 'canned', 65.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [158, 2, 'Pineapple crushed/tidbits/chunks', null, 'canned', 50.00, '1/3 cup', false, false, false, false, false, true, true, true, false, null],
            [159, 2, 'Pineapple slice', null, 'canned', 40.00, '1 ring', false, false, false, false, false, true, true, true, false, null],
            [160, 2, 'Strawberries, frozen, unsweetened', null, 'canned', 130.00, '3/4 cup or 26 pcs', false, false, false, false, false, true, true, true, false, null],
            [161, 2, 'Strawberries, heavy syrup', null, 'canned', 45.00, '1/4 cup or 7 pcs', false, false, false, false, false, true, true, true, false, null],
            [162, 2, 'Champoy', null, 'dried', 10.00, '2 pieces', false, false, false, false, false, true, true, true, false, null],
            [163, 2, 'Dates', null, 'dried', 15.00, '2 pieces', false, false, false, false, false, true, true, true, false, null],
            [164, 2, 'Dikyam', null, 'dried', 15.00, '2 pieces', false, false, false, false, false, true, true, true, false, null],
            [165, 2, 'Mango chips', null, 'dried', 10.00, '2 pieces', false, false, false, false, false, true, true, true, false, null],
            [166, 2, 'Prunes', null, 'dried', 15.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [167, 2, 'Raisins', 'Pasas', 'dried', 15.00, '2 tbsp', false, false, false, false, false, true, true, true, false, null],
            [168, 3, 'Milk, carabao', 'Gatas ng kalabaw', 'whole', 200.00, '3/4 cup', false, false, false, false, false, true, true, true, false, 'Carabao milk: +2 fat exchanges'],
            [169, 3, 'Milk, cow', null, 'whole', 250.00, '1 cup', false, false, false, false, false, true, true, true, false, null],
            [170, 3, 'Milk, evaporated', null, 'whole', 125.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [171, 3, 'Milk, evaporated, filled', null, 'whole', 125.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [172, 3, 'Milk, goat', 'Gatas ng kambing', 'whole', 250.00, '1 cup', false, false, false, false, false, true, true, true, false, null],
            [173, 3, 'Milk, recombined', null, 'whole', 200.00, '3/4 cup', false, false, false, false, false, true, true, true, false, null],
            [174, 3, 'Milk, powder, filled, instant', null, 'whole', 35.00, '5 tbsp, level', false, false, false, false, false, true, true, true, false, null],
            [175, 3, 'Milk, powder, full cream', null, 'whole', 35.00, '5 tbsp, level', false, false, false, false, false, true, true, true, false, null],
            [176, 3, 'Milk, low fat (1-2%)', null, 'low_fat', 250.00, '1 cup', false, false, false, false, false, true, true, true, false, null],
            [177, 3, 'Yogurt (low fat)', null, 'low_fat', 150.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [178, 3, 'Buttermilk', null, 'skim', 180.00, '3/4 cup', false, false, false, false, false, true, true, true, false, null],
            [179, 3, 'Milk, skim', 'Skim milk', 'skim', 250.00, '1 cup', false, false, false, false, false, true, true, true, false, null],
            [180, 3, 'Milk, powder, skim', null, 'skim', 25.00, '4 tbsp, level', false, false, false, false, false, true, true, true, false, null],
            [181, 3, 'Milk, powder, non-fat, instant', null, 'skim', 25.00, '4 tbsp, level', false, false, false, false, false, true, true, true, false, null],
            [182, 3, 'Yogurt, plain, skim', null, 'skim', 150.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [183, 4, 'Rice, protein-reduced', null, 'low_protein', 55.00, '1/3 cup', false, false, false, false, false, true, true, true, false, null],
            [184, 4, 'Ampaw, pinipig', 'Puffed rice', 'low_protein', 25.00, '2 pieces', false, false, false, false, false, true, true, true, false, null],
            [185, 4, 'Biko', null, 'low_protein', 40.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [186, 4, 'Cuchinta', null, 'low_protein', 60.00, '2 pieces', false, false, false, false, false, true, true, true, false, null],
            [187, 4, 'Sapin-sapin', null, 'low_protein', 75.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [188, 4, 'Cornstarch', null, 'low_protein', 25.00, '1/4 cup', false, false, false, false, false, true, true, true, false, null],
            [189, 4, 'Maja Blanca', null, 'low_protein', 65.00, '1/2 slice', false, false, false, false, false, true, true, true, false, null],
            [190, 4, 'Maja Mais', null, 'low_protein', 75.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [191, 4, 'Bihon', 'Rice noodles', 'low_protein', 100.00, '1 cup', false, false, false, false, false, true, true, true, false, null],
            [192, 4, 'Misua', 'Wheat vermicelli', 'low_protein', 100.00, '1 cup', false, false, false, false, false, true, true, true, false, null],
            [193, 4, 'Sotanghon', 'Glass noodles', 'low_protein', 100.00, '1 cup', false, false, false, false, false, true, true, true, false, null],
            [194, 4, 'Sweet potato noodles', null, 'low_protein', 100.00, '1 cup', false, false, false, false, false, true, true, true, false, null],
            [195, 4, 'Gabi', 'Taro', 'low_protein', 100.00, '3/4 cup, cubed', false, false, false, false, false, true, true, true, false, 'High potassium; limit in CKD'],
            [196, 4, 'Kamote, sweet potato (yellow)', 'Sweet potato', 'low_protein', 85.00, '1 pc or 3/4 cup cubed', false, false, false, false, false, true, true, true, false, null],
            [197, 4, 'Kamoteng kahoy', 'Cassava', 'low_protein', 85.00, '1 slice or 3/4 cup cubed', false, false, false, false, false, true, true, true, false, null],
            [198, 4, 'Kamoteng kahoy (bibingka)', 'Cassava bibingka', 'low_protein', 55.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [199, 4, 'Kamoteng kahoy (linupak)', null, 'low_protein', 55.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [200, 4, 'Kamoteng kahoy (pichi-pichi)', null, 'low_protein', 45.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [201, 4, 'Kamoteng kahoy (suman)', null, 'low_protein', 45.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [202, 4, 'Tugi', 'Wild yam', 'low_protein', 150.00, '1 pc or 1 1/4 cups cubed', false, false, false, false, false, true, true, true, false, null],
            [203, 4, 'Ubi', 'Purple yam', 'low_protein', 130.00, '1 cup, cubed', false, false, false, false, false, true, true, true, false, null],
            [204, 4, 'Saging, saba, nilaga', 'Boiled saba banana', 'low_protein', 65.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [205, 4, 'Sago, nilaga', 'Boiled sago', 'low_protein', 120.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [206, 4, 'Sago, tapioca', 'Tapioca', 'low_protein', 160.00, '3/4 cup', false, false, false, false, false, true, true, true, false, null],
            [207, 4, 'Bigas, maputi, sinaing', 'White rice, cooked', 'med_protein', 80.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [208, 4, 'Bigas, mapula, sinaing', 'Red rice, cooked', 'med_protein', 80.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [209, 4, 'Pinawa, sinaing', 'Brown rice, cooked', 'med_protein', 80.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [210, 4, 'Lugaw, thin consistency', 'Thin rice porridge', 'med_protein', 705.00, '4 1/2 cups', false, false, false, false, false, true, true, true, false, null],
            [211, 4, 'Lugaw, medium consistency', 'Medium rice porridge', 'med_protein', 435.00, '3 cups', false, false, false, false, false, true, true, true, false, null],
            [212, 4, 'Lugaw, thick consistency', 'Thick rice porridge', 'med_protein', 250.00, '1 1/2 cups', false, false, false, false, false, true, true, true, false, null],
            [213, 4, 'Ampaw, rice', 'Puffed rice', 'med_protein', 25.00, '2 pieces', false, false, false, false, false, true, true, true, false, null],
            [214, 4, 'Bibingka, galapong', null, 'med_protein', 45.00, '1/2 slice', false, false, false, false, false, true, true, true, false, null],
            [215, 4, 'Bibingka, malagkit', null, 'med_protein', 40.00, '1/2 slice', false, false, false, false, false, true, true, true, false, null],
            [216, 4, 'Bibingka, pinipig', null, 'med_protein', 50.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [217, 4, 'Espasol', null, 'med_protein', 35.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [218, 4, 'Kalamay, may latik', null, 'med_protein', 50.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [219, 4, 'Kalamay, ube', null, 'med_protein', 60.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [220, 4, 'Palitaw, walang niyog', null, 'med_protein', 50.00, '3 pieces', false, false, false, false, false, true, true, true, false, null],
            [221, 4, 'Puto, brown', null, 'med_protein', 50.00, '1/2 slice', false, false, false, false, false, true, true, true, false, null],
            [222, 4, 'Puto bumbong', null, 'med_protein', 40.00, '2 pieces', false, false, false, false, false, true, true, true, false, null],
            [223, 4, 'Puto maya', null, 'med_protein', 60.00, '1/2 piece', false, false, false, false, false, true, true, true, false, null],
            [224, 4, 'Puto, puti, calasiao', 'White puto', 'med_protein', 50.00, '3-4 pieces', false, false, false, false, false, true, true, true, false, null],
            [225, 4, 'Puto seko', null, 'med_protein', 25.00, '4 pieces', false, false, false, false, false, true, true, true, false, null],
            [226, 4, 'Puto seko, may niyog', null, 'med_protein', 25.00, '7 pieces', false, false, false, false, false, true, true, true, false, null],
            [227, 4, 'Suman marwekos, may niyog', null, 'med_protein', 50.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [228, 4, 'Suman na ibos', null, 'med_protein', 60.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [229, 4, 'Suman sa lihiya', null, 'med_protein', 55.00, '1/2 piece', false, false, false, false, false, true, true, true, false, null],
            [230, 4, 'Tamales', null, 'med_protein', 100.00, '2 pieces', false, false, false, false, false, true, true, true, false, null],
            [231, 4, 'Tikoy', null, 'med_protein', 40.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [232, 4, 'Tupig', null, 'med_protein', 35.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [233, 4, 'Apas', null, 'med_protein', 25.00, '7 pieces', false, false, false, false, false, true, true, true, false, null],
            [234, 4, 'Brohas', null, 'med_protein', 25.00, '5 pieces', false, false, false, false, false, true, true, true, false, null],
            [235, 4, 'Cake, mammon tostado', null, 'med_protein', 25.00, '2 1/2 pieces', false, false, false, false, false, true, true, true, false, null],
            [236, 4, 'Cuapao', null, 'med_protein', 35.00, '1/2 piece', false, false, false, false, false, true, true, true, false, null],
            [237, 4, 'Hopyang hapon', null, 'med_protein', 30.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [238, 4, 'Marie', 'Marie biscuit', 'med_protein', 25.00, '8 pieces', false, false, false, false, false, true, true, true, false, null],
            [239, 4, 'Pasencia', null, 'med_protein', 25.00, '7 pieces', false, false, false, false, false, true, true, true, false, null],
            [240, 4, 'Pianono', null, 'med_protein', 35.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [241, 4, 'Sponge cake', null, 'med_protein', 35.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [242, 4, 'Binatog', null, 'med_protein', 90.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [243, 4, 'Corn Flakes', null, 'med_protein', 25.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [244, 4, 'Mais butil, de lata', 'Canned corn kernels', 'med_protein', 160.00, '1 cup', false, false, false, false, false, true, true, true, false, null],
            [245, 4, 'Mais, cream style, de lata', 'Cream style corn', 'med_protein', 130.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [246, 4, 'Mais, durog', 'Ground corn', 'med_protein', 120.00, '1 cup', false, false, false, false, false, true, true, true, false, null],
            [247, 4, 'Mais sa busal', 'Corn on the cob', 'med_protein', 65.00, '1/2 piece', false, false, false, false, false, true, true, true, false, null],
            [248, 4, 'Patatas', 'Potato', 'med_protein', 170.00, '1 1/4 cup cubed', false, false, false, false, false, true, true, true, false, 'High potassium; limit in CKD'],
            [249, 4, 'Kastanyas, binusa', 'Roasted chestnuts', 'med_protein', 40.00, '8 pieces', false, false, false, false, false, true, true, true, false, null],
            [250, 4, 'Plantains', 'Saging na saba', 'med_protein', 80.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [251, 4, 'Bread, wheat', 'Wheat bread', 'high_protein', 40.00, '1 1/2 pieces', false, false, false, false, false, true, true, true, false, null],
            [252, 4, 'Ensaymada', null, 'high_protein', 35.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [253, 4, 'Hamburger bun', null, 'high_protein', 35.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [254, 4, 'Hotdog roll', null, 'high_protein', 35.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [255, 4, 'Loaf bread', 'Tasty bread', 'high_protein', 35.00, '2 pieces', false, false, false, false, false, true, true, true, false, null],
            [256, 4, 'Pan de bonete', null, 'high_protein', 35.00, '1 1/2 pieces', false, false, false, false, false, true, true, true, false, null],
            [257, 4, 'Pan de leche', null, 'high_protein', 35.00, '1/2 piece', false, false, false, false, false, true, true, true, false, null],
            [258, 4, 'Pan de limon', null, 'high_protein', 35.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [259, 4, 'Pan de monay', null, 'high_protein', 35.00, '1/2 piece', false, false, false, false, false, true, true, true, false, null],
            [260, 4, 'Pan de sal', 'Pandesal', 'high_protein', 35.00, '1 1/2 pieces', false, false, false, false, false, true, true, true, false, null],
            [261, 4, 'Pinagong', null, 'high_protein', 35.00, '1/2 piece', false, false, false, false, false, true, true, true, false, null],
            [262, 4, 'Pita bread, white', null, 'high_protein', 40.00, '1/2 piece', false, false, false, false, false, true, true, true, false, null],
            [263, 4, 'Pita bread, whole wheat', null, 'high_protein', 40.00, '1/2 piece', false, false, false, false, false, true, true, true, false, null],
            [264, 4, 'Tinapay, tostado', 'Toast', 'high_protein', 30.00, '5 pieces', false, false, false, false, false, true, true, true, false, null],
            [265, 4, 'Couscous', null, 'high_protein', 100.00, '1 cup', false, false, false, false, false, true, true, true, false, null],
            [266, 4, 'Pasta', null, 'high_protein', 70.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [267, 4, 'Udon', null, 'high_protein', 100.00, '1 cup', false, false, false, false, false, true, true, true, false, null],
            [268, 4, 'Balat ng lumpia', 'Spring roll wrapper', 'high_protein', 35.00, '7 pieces', false, false, false, false, false, true, true, true, false, null],
            [269, 4, 'Langka, buto', 'Jackfruit seeds', 'high_protein', 75.00, '14 pcs', false, false, false, false, false, true, true, true, false, null],
            [270, 4, 'Quinoa', null, 'high_protein', 95.00, '1 cup', false, false, false, false, false, true, true, true, false, null],
            [271, 5, 'Beef, shank', null, 'low_fat', 35.00, '1 slice, matchbox size', false, false, false, false, false, true, true, true, false, null],
            [272, 5, 'Beef, lean meat', null, 'low_fat', 35.00, '1 slice, matchbox size', false, false, false, false, false, true, true, true, false, null],
            [273, 5, 'Beef, round', null, 'low_fat', 35.00, '1 slice, matchbox size', false, false, false, false, false, true, true, true, false, null],
            [274, 5, 'Beef, tenderloin', null, 'low_fat', 35.00, '1 slice, matchbox size', false, false, false, false, false, true, true, true, false, null],
            [275, 5, 'Beef, porterhouse', null, 'low_fat', 35.00, '1 slice, matchbox size', false, false, false, false, false, true, true, true, false, null],
            [276, 5, 'Beef, sirloin', null, 'low_fat', 35.00, '1 slice, matchbox size', false, false, false, false, false, true, true, true, false, null],
            [277, 5, 'Carabeef, round', null, 'low_fat', 35.00, '1 slice, matchbox size', false, false, false, false, false, true, true, true, false, null],
            [278, 5, 'Carabeef, shank', null, 'low_fat', 35.00, '1 slice, matchbox size', false, false, false, false, false, true, true, true, false, null],
            [279, 5, 'Carabeef, lean with little fat', null, 'low_fat', 35.00, '1 slice, matchbox size', false, false, false, false, false, true, true, true, false, null],
            [280, 5, 'Carabeef, chuck', null, 'low_fat', 35.00, '1 slice, matchbox size', false, false, false, false, false, true, true, true, false, null],
            [281, 5, 'Carabeef, round steak', null, 'low_fat', 35.00, '1 slice, matchbox size', false, false, false, false, false, true, true, true, false, null],
            [282, 5, 'Carabeef, rump', null, 'low_fat', 35.00, '1 slice, matchbox size', false, false, false, false, false, true, true, true, false, null],
            [283, 5, 'Pork, tenderloin', null, 'low_fat', 35.00, '1 slice, matchbox size', false, false, false, false, false, true, true, true, false, null],
            [284, 5, 'Goat, shoulder', 'Kambing', 'low_fat', 40.00, '1 slice 8x2x2.5cm', false, false, false, false, false, true, true, true, false, null],
            [285, 5, 'Goat, leg', 'Kambing', 'low_fat', 40.00, '1 slice 8x2x2.5cm', false, false, false, false, false, true, true, true, false, null],
            [286, 5, 'Goat, shank', 'Kambing', 'low_fat', 40.00, '1 slice 8x2x2.5cm', false, false, false, false, false, true, true, true, false, null],
            [287, 5, 'Goat, breast', 'Kambing', 'low_fat', 35.00, '1 slice, mbs', false, false, false, false, false, true, true, true, false, null],
            [288, 5, 'Goat, neck', 'Kambing', 'low_fat', 40.00, '1 slice 8x2x2.5cm', false, false, false, false, false, true, true, true, false, null],
            [289, 5, 'Goat, back', 'Kambing', 'low_fat', 40.00, '1 slice 8x2x2.5cm', false, false, false, false, false, true, true, true, false, null],
            [290, 5, 'Goat, loin', 'Kambing', 'low_fat', 35.00, '1 slice, mbs', false, false, false, false, false, true, true, true, false, null],
            [291, 5, 'Goat, rib', 'Kambing', 'low_fat', 40.00, '1 slice 8x2x2.5cm', false, false, false, false, false, true, true, true, false, null],
            [292, 5, 'Chicken, white meat', null, 'low_fat', 30.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [293, 5, 'Chicken, breast', null, 'low_fat', 30.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [294, 5, 'Duck, wing', 'Pato', 'low_fat', 30.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [295, 5, 'Frog, meat', 'Palaka', 'low_fat', 30.00, '2 pieces, small', false, false, false, false, false, true, true, true, false, null],
            [296, 5, 'Liver', 'Atay', 'low_fat', 30.00, '1/4 cup', false, false, false, false, false, true, true, true, false, null],
            [297, 5, 'Lungs', 'Baga', 'low_fat', 35.00, '1/4 cup', false, false, false, false, false, true, true, true, false, null],
            [298, 5, 'Gizzard', 'Balunbalunan', 'low_fat', 25.00, '1/4 cup', false, false, false, false, false, true, true, true, false, null],
            [299, 5, 'Kidney', 'Bato', 'low_fat', 45.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [300, 5, 'Small intestine', 'Isaw', 'low_fat', 30.00, '1/4 cup', false, false, false, false, false, true, true, true, false, null],
            [301, 5, 'Chicken intestine', 'Isaw ng manok', 'low_fat', 20.00, '2 sticks', false, false, false, false, false, true, true, true, false, null],
            [302, 5, 'Blood', 'Dugo', 'low_fat', 35.00, '1/4 cup', false, false, false, false, false, true, true, true, false, null],
            [303, 5, 'Spleen', 'Lapay', 'low_fat', 45.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [304, 5, 'Omasum', 'Goto, libro', 'low_fat', 50.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [305, 5, 'Tendon', 'Litid', 'low_fat', 30.00, '1 slice, mbs', false, false, false, false, false, true, true, true, false, null],
            [306, 5, 'Heart', 'Puso', 'low_fat', 25.00, '1/4 cup', false, false, false, false, false, true, true, true, false, null],
            [307, 5, 'Alumahan', 'Indian mackerel', 'low_fat', 35.00, '1/2 piece', false, false, false, false, false, true, true, true, false, null],
            [308, 5, 'Porgy, fresh water', null, 'low_fat', 40.00, '1/2 slice', false, false, false, false, false, true, true, true, false, null],
            [309, 5, 'Milkfish', 'Bangus', 'low_fat', 35.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [310, 5, 'Mudfish / dalag', 'Dalag', 'low_fat', 40.00, '1/2 slice', false, false, false, false, false, true, true, true, false, null],
            [311, 5, 'Dalagang bukid', null, 'low_fat', 35.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [312, 5, 'Dilis, buo', 'Whole anchovy', 'low_fat', 35.00, '1/3 cup', false, false, false, false, false, true, true, true, false, null],
            [313, 5, 'Dilis, walang buto', 'Anchovy boneless', 'low_fat', 25.00, '1/4 cup', false, false, false, false, false, true, true, true, false, null],
            [314, 5, 'Dulong', 'Silverfish', 'low_fat', 50.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [315, 5, 'Galunggong', 'Mackerel scad', 'low_fat', 35.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [316, 5, 'Hasa-hasa', 'Short mackerel', 'low_fat', 35.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [317, 5, 'Hito', 'Catfish', 'low_fat', 35.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [318, 5, 'Labahita', 'Surgeonfish', 'low_fat', 40.00, '1/2 slice', false, false, false, false, false, true, true, true, false, null],
            [319, 5, 'Lapu-lapu', 'Grouper', 'low_fat', 40.00, '1/2 slice', false, false, false, false, false, true, true, true, false, null],
            [320, 5, 'Matangbaka', 'Bigeye scad', 'low_fat', 35.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [321, 5, 'Sapsap', 'Ponyfish', 'low_fat', 35.00, '2 pieces', false, false, false, false, false, true, true, true, false, null],
            [322, 5, 'Saramulyete', 'Goatfish', 'low_fat', 35.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [323, 5, 'Tambakol', 'Yellowfin tuna', 'low_fat', 35.00, '1/2 slice', false, false, false, false, false, true, true, true, false, null],
            [324, 5, 'Tamban', 'Sardinella', 'low_fat', 35.00, '1 1/2 pieces', false, false, false, false, false, true, true, true, false, null],
            [325, 5, 'Tawilis', 'Freshwater herring', 'low_fat', 30.00, '2 pieces', false, false, false, false, false, true, true, true, false, null],
            [326, 5, 'Tilapia', null, 'low_fat', 35.00, '1/2 slice', false, false, false, false, false, true, true, true, false, null],
            [327, 5, 'Tulingan', 'Frigate tuna', 'low_fat', 35.00, '1/2 slice', false, false, false, false, false, true, true, true, false, null],
            [328, 5, 'Alimango, alige', 'Mud crab fat', 'low_fat', 15.00, '1 tbsp', false, false, false, false, false, true, true, true, false, null],
            [329, 5, 'Alimango, laman', 'Mud crab meat', 'low_fat', 50.00, '1/3 cup', false, false, false, false, false, true, true, true, false, null],
            [330, 5, 'Alimasag, alige', 'Blue crab fat', 'low_fat', 25.00, '2 1/2 tbsp', false, false, false, false, false, true, true, true, false, null],
            [331, 5, 'Alimasag, laman', 'Blue crab meat', 'low_fat', 40.00, '1/3 cup', false, false, false, false, false, true, true, true, false, null],
            [332, 5, 'Balatan', 'Sea cucumber', 'low_fat', 120.00, '6 pieces', false, false, false, false, false, true, true, true, false, null],
            [333, 5, 'Pugita', 'Octopus', 'low_fat', 40.00, null, false, false, false, false, false, true, true, true, false, null],
            [334, 5, 'Pusit', 'Squid', 'low_fat', 50.00, '2 pieces', false, false, false, false, false, true, true, true, false, null],
            [335, 5, 'Talangka', 'River crab', 'low_fat', 25.00, '6 pieces', false, false, false, false, false, true, true, true, false, null],
            [336, 5, 'Hipon, alamang', 'Small shrimp', 'low_fat', 40.00, '1/3 cup', false, false, false, false, false, true, true, true, false, null],
            [337, 5, 'Hipon, sugpo', 'Tiger prawn', 'low_fat', 40.00, '1/2 piece', false, false, false, false, false, true, true, true, false, null],
            [338, 5, 'Hipon, suwahe', 'Small prawn', 'low_fat', 40.00, '4 pieces', false, false, false, false, false, true, true, true, false, null],
            [339, 5, 'Hipon, tagunton', 'Freshwater shrimp', 'low_fat', 40.00, null, false, false, false, false, false, true, true, true, false, null],
            [340, 5, 'Hipon, ulang', 'Freshwater prawn', 'low_fat', 40.00, null, false, false, false, false, false, true, true, true, false, null],
            [341, 5, 'Mollusks, surf clam / cockles', 'Halaan', 'low_fat', 60.00, '4 pieces', false, false, false, false, false, true, true, true, false, null],
            [342, 5, 'Abalone', null, 'low_fat', 30.00, '2-3 pieces', false, false, false, false, false, true, true, true, false, null],
            [343, 5, 'Kuhol, ginto', 'Golden snail', 'low_fat', 45.00, '12 pieces', false, false, false, false, false, true, true, true, false, null],
            [344, 5, 'Mollusks, hard clam', 'Tulya', 'low_fat', 60.00, '22 pieces', false, false, false, false, false, true, true, true, false, null],
            [345, 5, 'Cottage cheese', null, 'low_fat', 50.00, '1/3 cup', false, false, false, false, false, true, true, true, false, null],
            [346, 5, 'Tuna flakes, in brine', null, 'low_fat', 45.00, '1/4 cup', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [347, 5, 'Croaker, daing, plain', null, 'low_fat', 25.00, '8 pieces', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [348, 5, 'Alumahan, daing', 'Dried mackerel', 'low_fat', 25.00, '2 pieces', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [349, 5, 'Bakalaw, cod, daing', 'Dried cod', 'low_fat', 25.00, '1/3 piece', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [350, 5, 'Bisugo, daing', 'Dried threadfin', 'low_fat', 25.00, '1 piece', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [351, 5, 'Biyang puti, daing', 'Dried goby', 'low_fat', 25.00, '11 pcs small', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [352, 5, 'Lapu-lapu, daing', 'Dried grouper', 'low_fat', 25.00, '1 piece', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [353, 5, 'Malasugi, daing', 'Dried swordfish', 'low_fat', 20.00, '3 1/2 pieces', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [354, 5, 'Sapsap, daing', 'Dried ponyfish', 'low_fat', 25.00, '7 pieces', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [355, 5, 'Tamban, daing', 'Dried sardine', 'low_fat', 25.00, '2 pieces', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [356, 5, 'Tanigi, daing', 'Dried wahoo', 'low_fat', 25.00, null, true, false, false, false, false, true, true, true, false, 'High sodium'],
            [357, 5, 'Alamang, tuyo', 'Dried small shrimp', 'low_fat', 15.00, '1/2 cup', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [358, 5, 'Ayungin, tuyo', 'Dried silver perch', 'low_fat', 15.00, null, true, false, false, false, false, true, true, true, false, 'High sodium'],
            [359, 5, 'Dilis, tuyo', 'Dried anchovy', 'low_fat', 15.00, '13 pieces', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [360, 5, 'Hibe', 'Dried shrimp', 'low_fat', 25.00, '4 tbsp', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [361, 5, 'Pusit, tuyo', 'Dried squid', 'low_fat', 15.00, '2 pieces', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [362, 5, 'Sapsap, tuyo', 'Dried ponyfish', 'low_fat', 20.00, '4 pieces', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [363, 5, 'Tamban, tuyo', 'Dried sardinella', 'low_fat', 20.00, '2 pieces', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [364, 5, 'Galunggong, tinapa', 'Smoked mackerel scad', 'low_fat', 25.00, '1/2 piece', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [365, 5, 'Tamban, tinapa', 'Smoked sardinella', 'low_fat', 25.00, '3 pieces', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [366, 5, 'Tunsoy, tinapa', 'Smoked tunsoy', 'low_fat', 25.00, '3 pieces', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [367, 5, 'Beef, paypay, laman, lean', 'Beef plate', 'med_fat', 35.00, '1 slice, mbs', false, false, false, false, false, true, true, true, false, null],
            [368, 5, 'Beef, brisket', null, 'med_fat', 35.00, '1 slice, mbs', false, false, false, false, false, true, true, true, false, null],
            [369, 5, 'Pork, pata, leg', 'Pata', 'med_fat', 35.00, '1 slice, mbs', false, false, false, false, false, true, true, true, false, null],
            [370, 5, 'Chicken, leg / drumstick', 'Paa ng manok', 'med_fat', 35.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [371, 5, 'Chicken, thigh', 'Hita ng manok', 'med_fat', 35.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [372, 5, 'Chicken, wing', 'Pakpak ng manok', 'med_fat', 35.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [373, 5, 'Chicken, ulo', 'Chicken head', 'med_fat', 50.00, '2 pieces', false, false, false, false, false, true, true, true, false, null],
            [374, 5, 'Duck, thigh', 'Pato', 'med_fat', 35.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [375, 5, 'Duck, back', 'Pato', 'med_fat', 30.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [376, 5, 'Duck, breast', 'Pato', 'med_fat', 35.00, '1 slice, mbs', false, false, false, false, false, true, true, true, false, null],
            [377, 5, 'Goat, flank', 'Kambing', 'med_fat', 35.00, '1 slice, mbs', false, false, false, false, false, true, true, true, false, null],
            [378, 5, 'Small intestine, carabeef', null, 'med_fat', 35.00, '1/4 cup', false, false, false, false, false, true, true, true, false, null],
            [379, 5, 'Goto, tripe, beef', 'Goto', 'med_fat', 85.00, '3/4 cup', false, false, false, false, false, true, true, true, false, null],
            [380, 5, 'Utak, brain', 'Brain', 'med_fat', 45.00, '1/4 cup', false, false, false, false, false, true, true, true, false, null],
            [381, 5, 'Chicken egg, whole', 'Itlog ng manok', 'med_fat', 55.00, '1 piece medium', false, false, false, false, false, true, true, true, false, null],
            [382, 5, 'Duck egg, whole, salted', 'Itlog ng pato', 'med_fat', 55.00, '1 piece medium', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [383, 5, 'Quail egg', 'Itlog ng pugo', 'med_fat', 55.00, '7 pieces small', false, false, false, false, false, true, true, true, false, null],
            [384, 5, 'Karpa', 'Carp', 'med_fat', 35.00, '1/2 piece', false, false, false, false, false, true, true, true, false, null],
            [385, 5, 'Cheddar cheese, processed', null, 'med_fat', 30.00, '1 slice', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [386, 5, 'Bangus, tinapa', 'Smoked milkfish', 'med_fat', 30.00, '1 slice', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [387, 5, 'Salmon sa mantika', 'Canned salmon in oil', 'med_fat', 45.00, '3 slices', false, false, false, false, false, true, true, true, false, null],
            [388, 5, 'Sardinas sa tomato sauce', 'Canned sardines', 'med_fat', 80.00, '2 pieces', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [389, 5, 'Tuna spread', null, 'med_fat', 25.00, '2 tbsp', false, false, false, false, false, true, true, true, false, null],
            [390, 5, 'Karne Norte, de lata', 'Canned corned beef', 'med_fat', 45.00, '1/4 cup', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [391, 5, 'Sausage, ham', null, 'med_fat', 55.00, '2 pieces', true, false, false, false, false, true, true, true, false, 'High sodium'],
            [392, 5, 'Tofu', 'Soft tofu', 'med_fat', 100.00, '1/2 cup', false, false, false, false, false, true, true, true, false, null],
            [393, 5, 'Tokwa', 'Firm tofu', 'med_fat', 70.00, '1 piece', false, false, false, false, false, true, true, true, false, null],
            [394, 5, 'Chick, one-day-old, fried', null, 'med_fat', 35.00, '2 pieces', false, false, false, false, false, true, true, true, false, null],
            [395, 5, 'Manok paa, barbeque', 'Chicken feet BBQ', 'med_fat', 35.00, '4 pieces', false, false, false, false, false, true, true, true, false, null],
            [396, 5, 'Manok ulo, barbeque', 'Chicken head BBQ', 'med_fat', 35.00, '3 pieces', false, false, false, false, false, true, true, true, false, null],
            [397, 5, 'Beef, flank, camto', null, 'high_fat', 35.00, '1 slice, mbs', false, false, false, false, false, true, true, true, false, null],
            [398, 5, 'Beef, plate, tadyang', 'Beef ribs', 'high_fat', 35.00, '1 slice, mbs', false, false, false, false, false, true, true, true, false, null],
            [399, 5, 'Pork, kasim, picnic', null, 'high_fat', 35.00, '1 slice, mbs', false, false, false, false, false, true, true, true, false, null],
            [400, 5, 'Liempo, belly, less fat', 'Pork belly', 'high_fat', 35.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [401, 5, 'Pork, pigi, ham', 'Pork ham', 'high_fat', 35.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [402, 5, 'Tadyang, spare rib', 'Spare ribs', 'high_fat', 35.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [403, 5, 'Dila', 'Tongue', 'high_fat', 35.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [404, 5, 'Isaw ng baboy, barbeque', 'Pork intestine BBQ', 'high_fat', 35.00, '1/4 cup', false, false, false, false, false, true, true, true, false, null],
            [405, 5, 'Puso, manok', 'Chicken heart', 'high_fat', 35.00, '7 pieces', false, false, false, false, false, true, true, true, false, null],
            [406, 5, 'Tenga, baboy, barbeque', 'Pork ear BBQ', 'high_fat', 35.00, '1 slice', false, false, false, false, false, true, true, true, false, null],
            [407, 5, 'Mani, peanut with skin, roasted', 'Mani', null, null, null, false, false, false, false, false, true, true, true, false, null],
            [408, 5, 'Mani, without skin, roasted', 'Mani', null, null, null, false, false, false, false, false, true, true, true, false, null],
            [409, 5, 'Balut', null, 'high_fat', null, null, false, false, false, false, false, true, true, true, false, null],
            [410, 5, 'Penoy', null, 'high_fat', null, null, false, false, false, false, false, true, true, true, false, null],
            [411, 5, 'Pata, buo', 'Whole pork leg', 'high_fat', null, null, false, false, false, false, false, true, true, true, false, null],
            [412, 5, 'Feta cheese', null, 'high_fat', null, null, true, false, false, false, false, true, true, true, false, 'High sodium'],
            [413, 5, 'Gouda cheese', null, 'high_fat', null, null, true, false, false, false, false, true, true, true, false, 'High sodium'],
            [414, 5, 'Parmesan, grated', null, 'high_fat', null, null, true, false, false, false, false, true, true, true, false, 'High sodium'],
            [415, 5, 'Pimiento cheese', null, 'high_fat', null, null, true, false, false, false, false, true, true, true, false, 'High sodium'],
            [416, 5, 'Keso de bola', 'Edam cheese', 'high_fat', null, null, true, false, false, false, false, true, true, true, false, 'High sodium'],
            [417, 5, 'Sardinas, Spanish style', null, 'high_fat', null, null, true, false, false, false, false, true, true, true, false, 'High sodium'],
            [418, 5, 'Tuna flakes in vegetable oil', null, 'high_fat', null, null, false, false, false, false, false, true, true, true, false, null],
            [419, 5, 'Longganisa, chorizo', 'Longganisa', 'high_fat', null, null, true, false, false, false, false, true, true, true, false, 'High Na and fat'],
            [420, 5, 'Sausage, frankfurter', 'Hotdog', 'high_fat', null, null, true, false, false, false, false, true, true, true, false, 'High sodium'],
            [421, 5, 'Sausage, salami', null, 'high_fat', null, null, true, false, false, false, false, true, true, true, false, 'High sodium'],
            [422, 6, 'Avocado', 'Abukado', 'monounsaturated', 65.00, '12.5x6.5x2cm piece', false, false, false, false, false, true, true, true, false, null],
            [423, 6, 'Mantika, oil (olive/peanut)', 'Mantika', 'monounsaturated', 5.00, '1 tsp', false, false, false, false, false, true, true, true, false, null],
            [424, 6, 'Peanut butter', null, 'monounsaturated', 10.00, '1/2 tbsp', false, false, false, false, false, true, true, true, false, null],
            [425, 6, 'Shortening', null, 'monounsaturated', 5.00, '1 tsp', false, false, false, false, false, true, true, true, false, null],
            [426, 6, 'Almond', null, 'monounsaturated', 8.00, '7 pieces', false, false, false, false, false, true, true, true, false, null],
            [427, 6, 'Cashew nut, roasted', 'Kasuy', 'monounsaturated', 9.00, '6 pieces, whole', false, false, false, false, false, true, true, true, false, null],
            [428, 6, 'Macadamia', null, 'monounsaturated', 7.00, '5 pieces', false, false, false, false, false, true, true, true, false, null],
            [429, 6, 'Mixed nuts', null, 'monounsaturated', 7.00, '1 tbsp', false, false, false, false, false, true, true, true, false, null],
            [430, 6, 'Pili nut', 'Pili', 'monounsaturated', 7.00, '5 pieces', false, false, false, false, false, true, true, true, false, null],
            [431, 6, 'Sunflower seeds', null, 'monounsaturated', 8.00, '1 tbsp', false, false, false, false, false, true, true, true, false, null],
            [432, 6, 'Patani seeds', null, 'monounsaturated', 10.00, '5 pieces', false, false, false, false, false, true, true, true, false, null],
            [433, 6, 'Aseyte, oil, marine', 'Fish oil', 'polyunsaturated', null, null, false, false, false, false, false, true, true, true, false, null],
            [434, 6, 'Fish oil, cod liver', null, 'polyunsaturated', null, null, false, false, false, false, false, true, true, true, false, null],
            [435, 6, 'Oil (canola, corn, flaxseed, sesame, soybean, sunflower)', null, 'polyunsaturated', null, null, false, false, false, false, false, true, true, true, false, null],
            [436, 6, 'Walnut', null, 'polyunsaturated', null, null, false, false, false, false, false, true, true, true, false, null],
            [437, 6, 'Flaxseeds', 'Linseed', 'polyunsaturated', null, null, false, false, false, false, false, true, true, true, false, null],
            [438, 6, 'Kalabasa seeds', 'Squash seeds', 'polyunsaturated', null, null, false, false, false, false, false, true, true, true, false, null],
            [439, 6, 'Linga', 'Sesame seeds', 'polyunsaturated', null, null, false, false, false, false, false, true, true, true, false, null],
            [440, 6, 'Pakwan seeds', 'Watermelon seeds', 'polyunsaturated', null, null, false, false, false, false, false, true, true, true, false, null],
            [441, 6, 'Bacon', null, 'saturated', null, null, false, false, false, false, false, true, false, true, false, 'High Na and sat fat'],
            [442, 6, 'Cream cheese', null, 'saturated', null, null, false, false, false, false, false, true, false, true, false, null],
            [443, 6, 'Cream, all purpose', null, 'saturated', null, null, false, false, false, false, false, true, false, true, false, null],
            [444, 6, 'Cream, fluid, whipping', null, 'saturated', null, null, false, false, false, false, false, true, false, true, false, null],
            [445, 6, 'Cream, whipped', null, 'saturated', null, null, false, false, false, false, false, true, false, true, false, null],
            [446, 6, 'Krema', 'Local cream', 'saturated', null, null, false, false, false, false, false, true, false, true, false, null],
            [447, 6, 'Lard', 'Mantika ng baboy', 'saturated', null, null, false, false, false, false, false, true, false, true, false, 'High sat fat'],
            [448, 6, 'Latik', 'Coconut caramel', 'saturated', null, null, false, false, false, false, false, true, false, true, false, null],
            [449, 6, 'Butter', null, 'saturated', null, null, false, false, false, false, false, true, false, true, false, 'High sat fat'],
            [450, 6, 'Butter, light', null, 'saturated', null, null, false, false, false, false, false, true, false, true, false, null],
            [451, 6, 'Oil, coconut', 'Langis ng niyog', 'saturated', null, null, false, false, false, false, false, true, false, true, false, 'High sat fat'],
            [452, 6, 'Oil, coconut (MCT)', null, 'saturated', null, null, false, false, false, false, false, true, false, true, false, null],
            [453, 6, 'Oil, coconut (virgin/extra virgin)', 'VCO', 'saturated', null, null, false, false, false, false, false, true, false, true, false, null],
            [454, 6, 'Oil, palm', null, 'saturated', null, null, false, false, false, false, false, true, false, true, false, 'High sat fat'],
            [455, 6, 'Margarine', null, 'saturated', null, null, false, false, false, false, false, true, false, true, false, null],
            [456, 6, 'Mayonnaise', null, 'saturated', null, null, false, false, false, false, false, true, false, true, false, 'High sodium'],
            [457, 6, 'Mayonnaise, diet', null, 'saturated', null, null, false, false, false, false, false, true, false, true, false, null],
            [458, 6, 'Mayonnaise, light', null, 'saturated', null, null, false, false, false, false, false, true, false, true, false, null],
            [459, 6, 'Coconut cream', 'Kakang gata', 'saturated', null, null, false, false, false, false, false, true, false, true, false, 'High sat fat'],
            [460, 6, 'Coconut meat, mature', 'Niyog, hinog', 'saturated', null, null, false, false, false, false, false, true, false, true, false, null],
            [461, 6, 'Salad dressing', null, 'saturated', null, null, false, false, false, false, false, true, false, true, false, 'High sodium'],
            [462, 6, 'Sandwich spread', null, 'saturated', null, null, false, false, false, false, false, true, false, true, false, null],
            [463, 6, 'Sitsarong baboy / balat', 'Pork rinds', 'saturated', null, null, false, false, false, false, false, true, false, true, false, 'High Na and fat'],
            [464, 6, 'Sour cream', null, 'saturated', null, null, false, false, false, false, false, true, false, true, false, null],
            [465, 6, 'Beef tallow', null, 'saturated', null, null, false, false, false, false, false, true, false, true, false, 'High sat fat'],
            [466, 7, 'Arnibal', 'Sugar syrup', 'sugar', 5.00, '1 tsp', false, false, false, false, false, false, true, true, false, null],
            [467, 7, 'Asukal', 'Sugar', 'sugar', 5.00, '1 tsp', false, false, false, false, false, false, true, true, false, null],
            [468, 7, 'Banana chips', null, 'sugar', 5.00, '2 pieces', false, false, false, false, false, false, true, true, false, null],
            [469, 7, 'Bukayo', 'Coconut candy', 'sugar', 5.00, '1 piece', false, false, false, false, false, false, true, true, false, null],
            [470, 7, 'Candy', null, 'sugar', 5.00, '1 piece', false, false, false, false, false, false, true, true, false, null],
            [471, 7, 'Champoy', null, 'sugar', 5.00, '1 piece', false, false, false, false, false, false, true, true, false, null],
            [472, 7, 'Cherry, in syrup', null, 'sugar', 20.00, '5 pieces', false, false, false, false, false, false, true, true, false, null],
            [473, 7, 'Chewing gum / bubble gum', null, 'sugar', 5.00, '1-2 pieces', false, false, false, false, false, false, true, true, false, null],
            [474, 7, 'Chocolate', null, 'sugar', 5.00, '2 pieces', false, false, false, false, false, false, true, true, false, null],
            [475, 7, 'Coco Sugar', null, 'sugar', 5.00, '1 tsp', false, false, false, false, false, false, true, true, false, null],
            [476, 7, 'Coco syrup', null, 'sugar', 5.00, '1 tsp', false, false, false, false, false, false, true, true, false, null],
            [477, 7, 'Dates, pitted', null, 'sugar', 5.00, '1 piece', false, false, false, false, false, false, true, true, false, null],
            [478, 7, 'Dikyam', null, 'sugar', 10.00, '1 piece', false, false, false, false, false, false, true, true, false, null],
            [479, 7, 'Dried jackfruit', 'Pinatuyong langka', 'sugar', 5.00, '1 piece', false, false, false, false, false, false, true, true, false, null],
            [480, 7, 'Dried kiwi', null, 'sugar', 5.00, '1 piece', false, false, false, false, false, false, true, true, false, null],
            [481, 7, 'Dried mango', 'Pinatuyong mangga', 'sugar', 5.00, '1 piece', false, false, false, false, false, false, true, true, false, null],
            [482, 7, 'Dried papaya chunks', null, 'sugar', 5.00, '1 piece', false, false, false, false, false, false, true, true, false, null],
            [483, 7, 'Dried pineapple', null, 'sugar', 5.00, '2 pieces', false, false, false, false, false, false, true, true, false, null],
            [484, 7, 'Dulce de Leche', null, 'sugar', 5.00, '1 tsp', false, false, false, false, false, false, true, true, false, null],
            [485, 7, 'Gatas, sweetened, kondensada', 'Condensed milk', 'sugar', 5.00, '1 tsp', false, false, false, false, false, false, true, true, false, null],
            [486, 7, 'Gulaman, assorted fruit flavor', 'Colored gelatin', 'sugar', 15.00, '1 piece', false, false, false, false, false, false, true, true, false, null],
            [487, 7, 'Jam and Jellies', null, 'sugar', 10.00, '2 tsp', false, false, false, false, false, false, true, true, false, null],
            [488, 7, 'Kiamoy', null, 'sugar', 15.00, '2 pieces', false, false, false, false, false, false, true, true, false, null],
            [489, 7, 'Leche flan', null, 'sugar', 10.00, '1 slice', false, false, false, false, false, false, true, true, false, null],
            [490, 7, 'Lokum', 'Turkish delight', 'sugar', 5.00, '1 piece', false, false, false, false, false, false, true, true, false, null],
            [491, 7, 'Marshmallow', null, 'sugar', 5.00, '3 pieces', false, false, false, false, false, false, true, true, false, null],
            [492, 7, 'Matamis na bao', 'Coconut jam', 'sugar', 5.00, '1 tsp', false, false, false, false, false, false, true, true, false, null],
            [493, 7, 'Nata de coco / nata de pina, sweetened', null, 'sugar', 15.00, '1 tbsp', false, false, false, false, false, false, true, true, false, null],
            [494, 7, 'Pakaskas / Panocha', 'Brown sugar block', 'sugar', 5.00, '1 tsp', false, false, false, false, false, false, true, true, false, null],
            [495, 7, 'Pasas', 'Raisins', 'sugar', 5.00, '1 tsp', false, false, false, false, false, false, true, true, false, null],
            [496, 7, 'Pastilyas (durian, gatas, langka)', null, 'sugar', 5.00, '1 piece', false, false, false, false, false, false, true, true, false, null],
            [497, 7, 'Prunes', null, 'sugar', 10.00, '2 pieces', false, false, false, false, false, false, true, true, false, null],
            [498, 7, 'Pulot', 'Molasses', 'sugar', 10.00, '2 tsp', false, false, false, false, false, false, true, true, false, null],
            [499, 7, 'Pulot-pukyutan', 'Honey', 'sugar', 5.00, '1 tsp', false, false, false, false, false, false, true, true, false, null],
            [500, 7, 'Sampaloc, candied', 'Candied tamarind', 'sugar', 5.00, '2 pieces', false, false, false, false, false, false, true, true, false, null],
            [501, 7, 'Taho, may arnibal at sago', 'Taho with syrup', 'sugar', 40.00, '1/4 cup', false, false, false, false, false, false, true, true, false, null],
            [502, 7, 'Tira-tira', 'Pulled sugar candy', 'sugar', 5.00, '1 piece', false, false, false, false, false, false, true, true, false, null],
            [503, 7, 'Ice candy', null, 'sweet_equivalent', 75.00, '1 piece', false, false, false, false, false, false, true, true, false, '= 3 sugar exchanges'],
            [504, 7, 'Ice drop', null, 'sweet_equivalent', 40.00, '1 piece', false, false, false, false, false, false, true, true, false, '= 1.5 sugar exchanges'],
            [505, 7, 'Kundol, candied', 'Candied winter melon', 'sweet_equivalent', 15.00, '1 piece', false, false, false, false, false, false, true, true, false, '= 2 sugar exchanges'],
            [506, 7, 'Polvoron', null, 'sweet_equivalent', 10.00, '1 piece', false, false, false, false, false, false, true, true, false, '= 2 sugar exchanges'],
            [507, 7, 'Rimas, candied', 'Candied breadfruit', 'sweet_equivalent', 35.00, '3 pieces', false, false, false, false, false, false, true, true, false, '= 6 sugar exchanges'],
            [508, 7, 'Ubedol, fudge, yam', null, 'sweet_equivalent', 20.00, '1 piece', false, false, false, false, false, false, true, true, false, '= 3 sugar exchanges'],
            [509, 7, 'Yema', null, 'sweet_equivalent', 25.00, '1 piece', false, false, false, false, false, false, true, true, false, '= 4 sugar exchanges'],
            [510, 1, 'Bagoong', 'Shrimp paste', 'free_condiment', null, 'As desired', true, false, false, false, false, true, false, true, true, '<16 kcal; high sodium'],
            [511, 1, 'Bouillon, fat free', 'Clear soup', 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [512, 1, 'Candy, hard, sugar free', null, 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [513, 1, 'Chili powder', null, 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [514, 1, 'Cinnamon', 'Kanela', 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [515, 1, 'Clear broth', null, 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [516, 1, 'Coffee, powder', 'Kape', 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [517, 1, 'Curry', null, 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [518, 1, 'Fish sauce', 'Patis', 'free_condiment', null, 'As desired', true, false, false, false, false, true, false, true, true, '<16 kcal; high sodium'],
            [519, 1, 'Flavoring extract', null, 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [520, 1, 'Garlic', 'Bawang', 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [521, 1, 'Gelatin, unsweetened', null, 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [522, 1, 'Ginger', 'Luya', 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [523, 1, 'Gum, sugar free', null, 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [524, 1, 'Herbs', 'Pampalasa', 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [525, 1, 'Hot pepper sauce', null, 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [526, 1, 'Kalamansi', 'Calamansi', 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [527, 1, 'Kamias', 'Bilimbi', 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [528, 1, 'Lemon', null, 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [529, 1, 'Miso', null, 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [530, 1, 'Mustard', null, 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [531, 1, 'Oregano', null, 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [532, 1, 'Paprika', null, 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [533, 1, 'Pepper corn', 'Paminta', 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [534, 1, 'Pimiento', null, 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [535, 1, 'Saffron', null, 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [536, 1, 'Soy sauce', 'Toyo', 'free_condiment', null, 'As desired', true, false, false, false, false, true, false, true, true, '<16 kcal; high sodium'],
            [537, 1, 'Spices', 'Pampalasa', 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [538, 1, 'Tea', 'Tsaa', 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [539, 1, 'Turmeric', 'Luyang dilaw', 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [540, 1, 'Vinegar', 'Suka', 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [541, 1, 'Worcestershire sauce', null, 'free_condiment', null, 'As desired', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [542, 1, 'Barbecue sauce', null, 'free_condiment_measured', null, '1 tbsp', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [543, 1, 'Banana catsup', null, 'free_condiment_measured', null, '2 tsp', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [544, 1, 'Gravy', null, 'free_condiment_measured', null, '1 tbsp', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [545, 1, 'Lechon sauce', null, 'free_condiment_measured', null, '1 tbsp', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [546, 1, 'Pickle', 'Atsara', 'free_condiment_measured', null, '2 tbsp', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [547, 1, 'Sweet chili sauce', null, 'free_condiment_measured', null, '2 tsp', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [548, 1, 'Tomato catsup', null, 'free_condiment_measured', null, '1 tbsp', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [549, 1, 'Tomato paste', null, 'free_condiment_measured', null, '2 tbsp', false, false, false, false, false, true, true, true, true, '<16 kcal'],
            [550, 1, 'Tomato sauce', null, 'free_condiment_measured', null, '2 tbsp', false, false, false, false, false, true, true, true, true, '<16 kcal']
        ];

    }
}
